### PR TITLE
add check_file_exists plugin

### PR DESCRIPTION
**Pull request by cwjohnston**

### CODE REVIEW

**Comment by jkerry** [comment]
LGTM. Previous pull requests caused a merge conflict on README.  can you resolve that @cwjohnston ? 

@quaggoth  I'd like to get your opinion on these before merging it.

**Comment by quaggoth** [comment]
@jkerry - Looks great to me. I can add some tests later if I can find some downtime.

**Comment by cwjohnston** [comment]
Conflict resolved 👍 

Sorry about the lack of tests, I have some learning to do on that front. 😅

**Comment by arcanericky** [comment]
All good @cwjohnston. I've found the unit tests to be more difficult than the main code itself. So much that I think I learn more Go with writing unit tests than the mainline code.

If I don't find time to write the tests for this check I'll eventually file an issue so perhaps someone will run with it.

Thanks for the new check.

**Comment by quaggoth** [comment]
Thanks @cwjohnston. New checks are especially welcome. And the documentation is a great bonus for us.

**Pull request merged**
